run_config:
  output: classification_artifacts
  
load_data:
  order_by: 
    - machineID
    - time_in_cycles

data_cleaning:
  detect_negative: True
  numeric_column_start: 3
  numeric_column_end: 18

feature_engineering:
  RUL_max_percentage: 0.75

model_training:
  one_hot_encode: 
    - model
  validation_size: 0.2
  random_state: 42
  smote_random_state: 42
  LSTM: 
    drop_out: 
    - 0
    - 0.2
    initial_learning_rate: 
    - 0.05
    - 0.01
    cv: 2
    tuning_epochs: 10
    tuning_batch_size: 128
    tuning_verbose: 2
    patience: 5
    fitting_epochs: 50
    fitting_batch_size: 128
    fitting_verbose: 2
  Logistic: 
    C: 
    - 0.1
    - 0.2
    penalty: 
    - l2
    cv: 2
  XGB:
    n_estimators: 
    - 200
    - 500
    learning_rate: 
    - 0.001
    - 0.01
    max_depth: 
    - 2
    - 4
    gamma: 
    - 0
    - 0.5
    subsample: 
    - 0.75
    - 1
    colsample_bytree:
    - 0.5
    - 0.7
    n_jobs: 16
    verbose: True
    cv: 2

model_comparison:
  metric_to_compare:
    - Recall
    - Precision
    - AUC
  main_metric: Recall

inference:
  columns_to_drop:
  - Dataset
  - RUL_piecewise
  one_hot_encode:
  - model
  default_time: 24h
  available_times: 
  - 24h
  - 5d
  default_model: Best_Model
  available_models:
  - Best_Model
  - LSTM
  - CNN
  - XGB
  cutoff_value: 5

