data_cleaning:
  detect_negative: true
  numeric_column_end: 18
  numeric_column_start: 3
feature_engineering:
  RUL_max_percentage: 0.75
inference:
  available_models:
  - Best_Model
  - LSTM
  - CNN
  - XGB
  available_times:
  - 24h
  - 5d
  columns_to_drop:
  - Dataset
  - RUL_piecewise
  cutoff_value: 5
  default_model: Best_Model
  default_time: 24h
  one_hot_encode:
  - model
load_data:
  order_by:
  - machineID
  - time_in_cycles
model_comparison:
  main_metric: RMSE
  metric_to_compare:
  - RMSE
model_training:
  CNN:
    cv: 2
    drop_out:
    - 0
    - 0.2
    fitting_batch_size: 128
    fitting_epochs: 50
    fitting_verbose: 2
    initial_learning_rate:
    - 0.001
    - 0.01
    kernel_size: 3
    patience: 5
    pool_size: 2
    tuning_batch_size: 128
    tuning_epochs: 10
    tuning_verbose: 2
  LSTM:
    cv: 2
    drop_out:
    - 0
    - 0.2
    fitting_batch_size: 128
    fitting_epochs: 50
    fitting_verbose: 2
    initial_learning_rate:
    - 0.05
    - 0.01
    patience: 5
    tuning_batch_size: 128
    tuning_epochs: 10
    tuning_verbose: 2
  XGB:
    cv: 2
    gamma:
    - 0
    - 0.5
    - 1.0
    learning_rate:
    - 0.001
    - 0.01
    max_depth:
    - 1
    - 2
    - 4
    n_estimators:
    - 200
    - 500
    n_jobs: 16
    subsample:
    - 0.75
    - 1
    verbose: true
  one_hot_encode:
  - model
  random_state: 42
  validation_size: 0.2
run_config:
  output: artifacts
